name: Sync S3 Bucket through CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'  # Specify your AWS region

      - name: Sync S3 bucket through CloudFront
        uses: aws-actions/s3-sync@v3
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          SOURCE_DIR: 'html5up-dimension'

      - name: Create CloudFront Invalidation
        run: aws cloudfront create-invalidation --distribution-id EF52U6XTHPA78 --paths "/*"